msg="\n\n\#\#\n\#\#\n\#\# This file was generated by a script. Don't edit it.\n\#\#\n\#\#"

# Targets for the page table simulator
all: ptsim ptsim-clock

# Make sure Python script is executable and copy shell script
ptsim: pt-sim.sh pt_sim.py
	chmod +x pt_sim.py
	cp pt-sim.sh ptsim
	chmod +x ptsim

# Make sure Python script is executable and copy shell script
ptsim-clock: pt-sim-clock.sh pt_sim.py
	chmod +x pt_sim.py
	cp pt-sim-clock.sh ptsim-clock
	chmod +x ptsim-clock

# Clean up generated files
clean:
	rm -f ptsim ptsim-clock
	rm -rf __pycache__



